export interface NexusFAQEntry {
  id: number;
  category: string;
  question: string;
  answer: string;
}

const entries: Array<[string, string, string]> = [
  ["Nexus Fundamentals", "What is NEXUS PROPERTY NETWORK™?", "NEXUS is a Pakistan-wide AI-powered real estate infrastructure platform connecting properties, people, trust, intelligence, leads, deals, and transactions in one ecosystem. It is designed to extend beyond listings into verification, agent infrastructure, investment intelligence, enterprise workflows, and governed AI."],
  ["Nexus Fundamentals", "Is NEXUS a property listing website?", "No. Listings are one layer. NEXUS also organizes discovery, verification, agent networks, lead protection, deal management, market intelligence, investment intelligence, agency operations, developer workflows, enterprise tools, and property intelligence."],
  ["Nexus Fundamentals", "What problem is NEXUS trying to solve?", "NEXUS addresses fragmentation between property information, participants, documents, leads, negotiations, verification, market intelligence, and transactions by connecting these layers into structured workflows."],
  ["Nexus Fundamentals", "What is the ultimate vision of NEXUS?", "The long-term vision is a real estate operating system organized as Pakistan → Province → City → Area → Society → Street → Property → Agent → Lead → Deal → Transaction."],
  ["Nexus Fundamentals", "Is NEXUS only for Lahore?", "No. The architecture is Pakistan-wide and targets 130+ cities and 5,000+ areas as the network expands."],
  ["Nexus Fundamentals", "Which industries can use NEXUS?", "Residential, commercial, agricultural, industrial, corporate, investment, development, housing societies, construction, marketing, management, verification, financing, and land acquisition workflows are supported by the architecture."],
  ["Nexus Fundamentals", "Who can use NEXUS?", "Owners, buyers, sellers, agents, agencies, investors, builders, developers, housing societies, corporate clients, property managers, legal consultants, surveyors, valuation experts, banking partners, and administrators can participate according to role permissions."],
  ["Property Discovery", "What types of properties can be listed on NEXUS?", "Residential homes, apartments, villas, farmhouses, shops, offices, buildings, warehouses, factories, industrial land, farms, orchards, projects, developments, joint ventures, and corporate assets can be represented."],
  ["Property Discovery", "How does NEXUS property discovery work?", "Users search by location, property type, budget, size, purpose, investment requirements, market information, and status. AI can organize and match approved opportunities without inventing availability."],
  ["Property Discovery", "Does NEXUS guarantee that every property is genuine?", "No. Unverified listings are not automatically genuine. NEXUS uses verification levels, evidence collection, risk signals, activity history, and human review where appropriate. Users must complete their own due diligence."],
  ["Property Discovery", "What does SAMPLE mean on NEXUS?", "SAMPLE properties are demonstrations used to explain the platform. They are not presented as real transaction opportunities."],
  ["Trust & Verification", "What is the NEXUS Trust Infrastructure?", "Trust Infrastructure organizes identity, property, ownership, documents, activity, and transaction verification in the sequence Identity → Property → Ownership → Documents → Activity → Transaction."],
  ["Trust & Verification", "What is Identity Verification?", "Identity Verification establishes that a person or organization has provided the information required for its role and applicable review level."],
  ["Trust & Verification", "What is Property Verification?", "Property Verification reviews available property information and evidence to determine whether the record is sufficiently supported for its verification level."],
  ["Trust & Verification", "What is Ownership Verification?", "Ownership Verification reviews evidence relating to a claimed ownership or legal relationship. NEXUS must not claim ownership verification without reviewed evidence."],
  ["Trust & Verification", "What is Document Verification?", "Document Verification reviews submitted documents for relevant information, consistency, completeness, duplicates, and risk indicators."],
  ["Trust & Verification", "What is Document Intelligence AI?", "Document Intelligence AI can assist with OCR, extraction, classification, consistency checks, metadata analysis, image analysis, duplicate detection, and risk signals. It does not replace legal or human review."],
  ["Trust & Verification", "Can AI determine whether a document is legally genuine?", "AI can identify anomalies and inconsistencies, but an AI signal is not definitive legal proof. Legal or specialist cases must escalate for human review."],
  ["Trust & Verification", "How does NEXUS handle suspected fake documents?", "A document can be flagged, added to a risk workflow, compared with available information, escalated for human review, and recorded in an audit trail."],
  ["Trust & Verification", "What is an audit trail?", "An audit trail records important verification actions, status changes, lead activity, deal milestones, document events, administrative actions, and AI workflow events."],
  ["Trust & Verification", "Will NEXUS integrate with government land records?", "The architecture can support authorized future integrations, but NEXUS must not claim a live government integration until it is implemented and verified."],
  ["Trust & Verification", "Does verification mean a property is guaranteed safe to buy?", "No. Verification reduces information uncertainty but cannot eliminate legal, financial, physical, or market risk. Professional due diligence remains necessary."],
  ["Agents & Agencies", "What is the NEXUS Agent Network?", "It connects property professionals with owners, buyers, sellers, leads, properties, and transactions through structured workflows."],
  ["Agents & Agencies", "What is a Verified Agent?", "A Verified Agent has completed the applicable NEXUS verification requirements for the relevant profile and role."],
  ["Agents & Agencies", "What information can an agent profile contain?", "A profile may include identity, specializations, coverage areas, verification status, AI interview information, activity, properties, reviews, and network status."],
  ["Agents & Agencies", "What is the AI Agent Interview?", "The AI interview collects structured information about experience, areas, specialization, services, professional approach, and market knowledge for the profile."],
  ["Agents & Agencies", "What is Agent Performance Intelligence?", "It organizes measurable signals such as lead response, lead activity, deal progress, client interactions, property activity, completion rates, and verification status. It does not replace judgment."],
  ["Agents & Agencies", "What is the NEXUS Agent quality-control system?", "Agents who repeatedly fail defined standards may lose network privileges or be removed, subject to policy, documented review, and applicable procedures."],
  ["Agents & Agencies", "Can an agent be removed from NEXUS?", "Yes, where platform rules, verification requirements, safety policies, or defined standards justify action after appropriate review."],
  ["Agents & Agencies", "What is an Agency account?", "An Agency account supports organizations managing multiple agents, properties, leads, clients, branches, and deals."],
  ["Lead Protection", "What is the NEXUS Lead Protection Engine?", "It creates a structured path from Lead → Qualification → Routing → Agent Matching → Lead Lock → Activity → Deal → Transaction."],
  ["Lead Protection", "What is Lead Qualification AI?", "It organizes intent, property requirements, budget, location, timing, suitability signals, and the next recommended action."],
  ["Lead Protection", "What is Lead Routing AI?", "It routes leads using area, specialization, availability, requirements, profile information, and network rules."],
  ["Lead Protection", "What is Lead Lock?", "Lead Lock is a paid mechanism giving an eligible agent a protected working period with recorded lock time, agent, lead, activity, and expiry."],
  ["Lead Protection", "How much does Lead Lock cost?", "The approved Lead Lock plan is 48 hours for PKR 500. There is currently no PKR 100 or 24-hour plan."],
  ["Lead Protection", "What happens if a Lead Lock expires?", "The lead can enter a recovery or reopening workflow according to its status and platform rules."],
  ["Lead Protection", "What is Lead Recovery?", "Lead Recovery prevents valuable opportunities from disappearing after inactivity or failed engagement by allowing eligible reopening and routing."],
  ["Lead Protection", "Can another agent receive a recovered lead?", "Yes, if the lead is reopened and eligible for reassignment under NEXUS rules."],
  ["Deal Infrastructure", "What is Deal Lock?", "Deal Lock structures an active transaction around the buyer, seller, agent, property, documents, milestones, communication, and payments."],
  ["Deal Infrastructure", "How much does Deal Lock cost?", "Approved Deal Lock pricing ranges from PKR 500 to PKR 5,000 depending on transaction complexity. Large arrangements may later use commercial percentage terms."],
  ["Deal Infrastructure", "What is a NEXUS Deal Room?", "A Deal Room can contain participants, property, offers, negotiations, documents, milestones, payment status, communication, and activity history."],
  ["Deal Infrastructure", "What deal statuses can NEXUS support?", "Typical statuses include New, Active, Negotiation, Documentation, Payment, and Closed."],
  ["Deal Infrastructure", "What is Negotiation AI?", "Negotiation AI organizes offers, counteroffers, history, requirements, conditions, and next actions. It does not make legally binding decisions independently."],
  ["Deal Infrastructure", "What is Commission Intelligence AI?", "It helps calculate, track, document, and manage commission-related information."],
  ["Deal Infrastructure", "What is Dispute Resolution AI?", "It organizes dispute information and relevant records for resolution workflows. It does not replace courts, lawyers, arbitrators, or authorized bodies."],
  ["NEXUS AI Workforce", "How many AI employees does NEXUS have?", "The official architecture contains 54 AI Employees organized into eight AI departments."],
  ["NEXUS AI Workforce", "What is NEXUS Master AI?", "Master AI is the central orchestration layer for understanding intent and coordinating the appropriate AI Employees."],
  ["NEXUS AI Workforce", "How does Master AI work?", "The intended chain is User → Master AI → Intent Detection → Department Selection → Employee Selection → Knowledge/Data → Reasoning → Permission Check → Workflow → Audit → Response."],
  ["NEXUS AI Workforce", "Are all 54 AI employees fully autonomous?", "Not necessarily. NEXUS follows phased automation. Employees may begin with information and intelligence, while sensitive actions remain permission-controlled and auditable."],
  ["NEXUS AI Workforce", "What are the eight AI departments?", "Core AI Workforce; Property Operations AI; Area & Market Intelligence AI; Lead & Deal Infrastructure AI; Agency & Enterprise AI; Industrial & Agriculture AI; Financial & Investment AI; Governance & OS AI."],
  ["NEXUS AI Workforce", "Who supervises the 54 AI employees?", "AI Admin monitors health, performance, logs, permissions, workflows, failures, escalations, safety, human review, and automation health."],
  ["NEXUS AI Workforce", "Can multiple AI employees work together?", "Yes. A request may combine Investment AI, Property Matching AI, Market Trend AI, Investment Zone AI, Property Pricing AI, Property Risk AI, ROI Intelligence AI, and Capital Advisory AI."],
  ["NEXUS AI Workforce", "Will AI remember previous conversations?", "The intended architecture includes persistent authorized memory linked to account and conversation history, subject to permissions, privacy, security, and data policies."],
  ["Property Intelligence", "What is Property Intelligence?", "It transforms raw property information into structured pricing, risk, matching, analytics, compliance, recommendations, and market context."],
  ["Property Intelligence", "What is a Property Twin?", "A Property Twin is a digital representation connecting a property’s physical, geographic, informational, media, verification, and analytical data."],
  ["Property Intelligence", "What is a Society Twin?", "A Society Twin represents a housing society or development environment as a structured digital intelligence layer."],
  ["Property Intelligence", "What is an Area Twin?", "An Area Twin connects property, market, development, demand, supply, commercial, and activity information for an area."],
  ["Property Intelligence", "What is a City Twin?", "A City Twin is a long-term digital representation of a city’s real estate ecosystem."],
  ["Property Intelligence", "What is the Pakistan Property Twin?", "It is the national vision of connecting property intelligence across Pakistan through Property → Society → Area → City → Pakistan."],
  ["Market & Investment Intelligence", "What is Area Intelligence?", "Area Intelligence combines properties, prices, transactions, development, commercial activity, projects, agents, demand, and supply."],
  ["Market & Investment Intelligence", "What is City Intelligence?", "City Intelligence analyzes residential, commercial, industrial, agricultural, project, investment, transaction, development, demand, and supply information."],
  ["Market & Investment Intelligence", "What is National Property Intelligence?", "It provides a broader view of Pakistan’s property ecosystem by connecting geographic, property, market, investment, and development information."],
  ["Market & Investment Intelligence", "What is Investment AI?", "Investment AI helps analyze opportunities using capital, location, property type, risk preference, investment horizon, and available market information."],
  ["Market & Investment Intelligence", "Does NEXUS guarantee ROI?", "No. Investment analysis is informational and depends on the quality, completeness, freshness, and accuracy of available data."],
  ["Market & Investment Intelligence", "What is ROI Intelligence AI?", "It analyzes potential returns using available financial and property information without guaranteeing outcomes."],
  ["Market & Investment Intelligence", "What is Property Risk AI?", "It identifies and organizes potential risk indicators relating to property, transaction, market, documents, and available evidence."],
  ["Developers & Projects", "What can developers do on NEXUS?", "Developers can eventually manage projects, units, leads, investors, buyers, marketing, verification, analytics, and AI tools."],
  ["Developers & Projects", "What is Project Intelligence?", "Project Intelligence connects development information with units, investors, buyers, marketing, verification, and analytics."],
  ["Developers & Projects", "Can NEXUS support housing societies?", "Yes. The architecture supports property intelligence, geographic intelligence, project information, verification workflows, and digital-twin concepts."],
  ["Media & Marketing AI", "What is Media AI?", "Media AI can transform property information, photos, videos, floor plans, location, and descriptions into reels, videos, graphics, social posts, presentations, and advertisements."],
  ["Media & Marketing AI", "Can NEXUS create property videos automatically?", "The architecture supports automated media workflows, but the level of automation depends on the tools and integrations actually implemented."],
  ["Dashboards", "What dashboard does a buyer get?", "Buyer Dashboard can include overview, saved properties, AI recommendations, searches, viewing requests, messages, negotiations, deals, verification, tours, and profile."],
  ["Dashboards", "What dashboard does a seller get?", "Seller Dashboard can include overview, properties, submissions, leads, offers, marketing, verification, deals, analytics, and messages."],
  ["Dashboards", "What dashboard does an agent get?", "Agent Dashboard can include overview, lead queue, locked leads, areas, clients, properties, deals, Deal Lock, commission, messages, and analytics."],
  ["Dashboards", "What dashboard does an investor get?", "Investor Dashboard can include opportunities, ROI, market intelligence, portfolio, projects, AI analysis, and risk information."],
  ["Dashboards", "What dashboard does a developer get?", "Developer Dashboard can include projects, units, leads, investors, marketing, verification, analytics, and AI tools."],
  ["Dashboards", "What does Admin Dashboard manage?", "Admin Mission Control can include users, properties, agents, agencies, projects, verification, leads, deals, fraud, disputes, AI, analytics, and system health."],
  ["Dashboards", "What is AI Admin Dashboard?", "AI Admin Dashboard supervises AI health, performance, employees, prompts, knowledge, automation, workflows, logs, models, safety, permissions, and human review."],
  ["Security & Governance", "How does NEXUS protect user data?", "The intended architecture includes authentication, authorization, RBAC, data and document protection, communication security, audit logs, fraud monitoring, AI safety, transaction security, and administrative controls."],
  ["Security & Governance", "What is RBAC?", "Role-Based Access Control ensures users receive permissions appropriate to their role; buyers, agents, developers, and administrators do not automatically share identical access."],
  ["Security & Governance", "Can AI perform sensitive actions automatically?", "Sensitive actions follow AI → Permission Check → Authorized Action → Audit. Unrestricted AI access is not the intended model."],
  ["Security & Governance", "What happens when AI is uncertain?", "AI should ask for more information, flag uncertainty, escalate to human review, avoid unsupported conclusions, and record the workflow where appropriate."],
  ["Payments & Transactions", "Does NEXUS process payments?", "The architecture supports payments for services, subscriptions, locks, verification, and approved transactions. Live providers depend on the implemented backend."],
  ["Payments & Transactions", "Does NEXUS guarantee a property transaction?", "No. NEXUS provides infrastructure and tools; the outcome remains subject to parties, legal requirements, documentation, verification, and regulations."],
  ["Payments & Transactions", "Does NEXUS guarantee that a buyer will get a property?", "No. NEXUS can support discovery, matching, verification, communication, and deal workflows, but cannot guarantee a transaction outcome."],
  ["Mobile & Digital Experience", "Will NEXUS work on mobile?", "Yes. The intended experience is responsive web and optimized mobile access, prioritizing Home, Search, AI, Saved, Messages, and Profile."],
  ["Mobile & Digital Experience", "Will NEXUS support 3D property experiences?", "The architecture supports future exterior, interior, floor, room, floor-plan, property, area, society, and city experiences."],
  ["FAQ & Knowledge System", "Why does NEXUS need a large FAQ system?", "Real estate creates questions across properties, buying, selling, renting, agents, verification, fraud, leads, deals, payments, AI, investment, pricing, privacy, and dashboards. A structured knowledge base makes those answers searchable and consistent."],
  ["NEXUS Constitution", "What is the NEXUS Constitution?", "It is the conceptual set of principles defining trust, verification, transparency, user protection, AI governance, data integrity, lead protection, deal protection, professional standards, and accountability."],
  ["NEXUS Constitution", "What is the NEXUS Trust Principle?", "No important property claim should be treated as verified without appropriate evidence."],
  ["NEXUS Constitution", "What is the NEXUS AI Principle?", "AI assists intelligence and workflows while remaining subject to permissions, evidence, safety controls, and human oversight where necessary."],
  ["NEXUS Constitution", "What is the NEXUS Data Principle?", "Important data should be structured, traceable, protected, and used according to authorized access and applicable policies."],
  ["NEXUS Constitution", "What is the NEXUS Lead Principle?", "A legitimate lead should have traceable activity and defined protection mechanisms."],
  ["NEXUS Constitution", "What is the NEXUS Deal Principle?", "A serious transaction should have structured participants, milestones, records, and accountability."],
  ["NEXUS Constitution", "What is the NEXUS Verification Principle?", "Verification should be based on evidence, not appearance."],
  ["NEXUS Constitution", "What is the NEXUS Transparency Principle?", "Users should understand what is verified, unverified, missing, determined by AI, uncertain, or awaiting human review."],
  ["NEXUS Constitution", "What is the NEXUS Human Oversight Principle?", "AI should not eliminate responsible human decision-making in sensitive property, legal, financial, or transactional matters."],
  ["NEXUS Constitution", "What is the NEXUS Accountability Principle?", "Important actions should be attributable to an authorized user, system workflow, or AI process and recorded where appropriate."],
  ["NEXUS Constitution", "What is the NEXUS Anti-Fraud Principle?", "The platform should continuously identify suspicious activity, inconsistent information, fraudulent behavior, spam, duplicate content, and risk signals."],
  ["The Future of NEXUS", "What is the long-term NEXUS roadmap?", "The roadmap moves from Property Platform to Property Intelligence, Trust Infrastructure, Lead Infrastructure, Deal Infrastructure, AI Workforce, Digital Twins, National Property Intelligence, and NEXUS OS."],
  ["The Future of NEXUS", "What is the ultimate NEXUS North Star?", "To create connected infrastructure where People + Properties + Places + Trust + Intelligence + Leads + Deals + Transactions operate through one network."],
  ["The Future of NEXUS", "What is NEXUS OS™ in one sentence?", "NEXUS OS™ is the operating intelligence layer designed to connect Pakistan’s real estate ecosystem."],
  ["The Future of NEXUS", "What is the NEXUS mission in one sentence?", "Make real estate more connected, transparent, intelligent, protected, and easier to navigate through technology, verification, and AI."],
  ["The Future of NEXUS", "Why should someone join NEXUS?", "NEXUS is designed as a network where property professionals, owners, buyers, sellers, investors, developers, and enterprises connect through property intelligence, trust infrastructure, protected leads, structured deals, and AI workflows."],
  ["The Future of NEXUS", "What is the NEXUS ecosystem in one line?", "Discover → Verify → Match → Protect → Negotiate → Transact → Learn."],
  ["The Future of NEXUS", "What is NEXUS ultimately trying to build?", "A digital infrastructure layer for Pakistan’s real estate industry: properties become intelligent, people identifiable, information structured, evidence traceable, leads protected, deals organized, AI coordinated, and transactions supported."],
];

export const nexusFAQ: NexusFAQEntry[] = entries.map(([category, question, answer], index) => ({ id: index + 1, category, question, answer }));
export const faqCategories = [...new Set(nexusFAQ.map((entry) => entry.category))];
