"use client";

import { useState } from "react";
import { aiAssistants } from "@/config/nexus-data";

export function AIDirectory() {
  const [selected, setSelected] = useState<(typeof aiAssistants)[number] | null>(null);
  const [query, setQuery] = useState("");
  const visible = aiAssistants.filter((assistant) => assistant.name.toLowerCase().includes(query.toLowerCase()) || assistant.department.toLowerCase().includes(query.toLowerCase()));
  return <section className="ai-directory section-padding" id="ai-assistants"><div className="section-heading-row"><div><p className="kicker">Nexus OS Workforce</p><h2>54 AI Assistants for every <em>property decision.</em></h2><p>Choose a specialist to explore its role. Live conversations, memory, speech, and approved data access will connect through authenticated AI services.</p></div><select className="ai-select" onChange={(event) => setSelected(aiAssistants.find((assistant) => String(assistant.id) === event.target.value) ?? null)} defaultValue=""><option value="">Select an AI Assistant</option>{aiAssistants.map((assistant) => <option value={assistant.id} key={assistant.id}>#{String(assistant.id).padStart(2, "0")} {assistant.name}</option>)}</select></div><div className="ai-directory-toolbar"><span>{visible.length} specialists available</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search assistants or departments" /></div><div className="ai-directory-grid">{visible.map((assistant) => <article className="ai-directory-card" key={assistant.id}><div className="ai-card-top"><span>#{String(assistant.id).padStart(2, "0")}</span><span className="ai-status"><i /> Ready</span></div><h3>{assistant.name}</h3><small>{assistant.department}</small><p>{assistant.description}</p><button className="button button-dark" onClick={() => setSelected(assistant)}>Chat with assistant <span>-&gt;</span></button></article>)}</div>{selected && <div className="ai-chat-backdrop" role="presentation" onClick={() => setSelected(null)}><section className="ai-chat-panel" role="dialog" aria-modal="true" aria-label={`${selected.name} chat`} onClick={(event) => event.stopPropagation()}><button className="ai-chat-close" onClick={() => setSelected(null)} aria-label="Close chat">×</button><p className="kicker">Nexus AI Assistant #{String(selected.id).padStart(2, "0")}</p><h3>{selected.name}</h3><p className="ai-chat-intro">I can help with {selected.department.toLowerCase()} questions using approved Nexus information. Connect the AI provider to enable live answers, memory, Urdu/Roman Urdu, and voice.</p><div className="ai-chat-messages"><div className="ai-message assistant-message">Tell me what property decision you are trying to make, and I&apos;ll guide you to the right next step.</div>{query && <div className="ai-message user-message">{query}</div>}</div><div className="ai-chat-input"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Ask about a property, area, lead, or deal" /><button className="button button-primary">Send</button></div><small className="ai-chat-note">Voice and live AI require a secure server-side provider connection.</small></section></div>}</section>;
}
