const roles = [
  ["Buyers", "Make property decisions with verified context, area intelligence, protected leads, and deal visibility.", "Property discovery", "Verified listings", "Area intelligence", "Buyer AI Employee", "Protected deals", "Investment opportunities", "/nexus/properties"],
  ["Sellers", "Turn property information into structured, reviewable opportunities while keeping ownership evidence central.", "Property listing", "Verification process", "Marketing assistance", "Lead management", "Deal protection", "Seller AI Employee", "/nexus/properties"],
  ["Agents", "Operate a protected lead and deal pipeline with clearer ownership, follow-up, performance, and commission context.", "Lead lock system", "Deal lock system", "CRM ecosystem", "Agent dashboard", "Agent AI Employee", "Performance analytics", "/nexus/agents"],
  ["Agencies", "Coordinate branches, teams, routing, revenue, and governed AI support from one operating layer.", "Agency creation", "Team management", "Branch management", "Lead distribution", "Revenue analytics", "Agency AI Workforce", "/nexus/agents"],
  ["Developers", "Manage projects, investor relationships, verification workflows, and project intelligence at portfolio scale.", "Project management", "Investor matching", "Marketing services", "Verification services", "Developer AI Employee", "Project intelligence", "/nexus/projects"],
  ["Investors", "Evaluate opportunities through recorded history, ROI intelligence, joint ventures, funding, and risk context.", "Land banking", "ROI intelligence", "Joint ventures", "Project funding", "Investor AI Employee", "Capital planning", "/nexus/intelligence"],
  ["Industrial users", "Explore factories, warehouses, industrial land, compliance records, and specialist AI workflows.", "Industrial properties", "Warehouses", "Factories", "Industrial land", "Compliance", "Industrial AI Employee", "/nexus/properties"],
  ["Corporate clients", "Manage multi-location portfolios, leasing, asset intelligence, transactions, and verification.", "Portfolio management", "Corporate leasing", "Asset intelligence", "Corporate transactions", "Corporate AI Employee", "Corporate verification", "/nexus/projects"],
  ["Government entities", "Use structured property transparency, market monitoring, verification, and national intelligence with controlled access.", "Property transparency", "Area intelligence", "Fraud detection", "Verification layer", "Market monitoring", "National data insights", "/coverage"],
] as const;

const foundation = [
  ["Real Estate Operating System", "Nexus is not a traditional property website. It coordinates discovery, verification, lead qualification, deal protection, and AI-assisted workflows so the platform acts as infrastructure rather than a listing shelf."],
  ["National Property Network", "Properties connect to areas, areas connect to cities, and cities connect to provinces. This property graph creates the context needed for matching, verification, analytics, and responsible expansion."],
  ["AI Workforce Platform", "Nexus uses specialized AI Employees instead of generic chatbots. Each employee has a defined role, scoped memory, confidence threshold, and escalation path under AI Admin supervision."],
] as const;

const differences = [
  ["Property portals", "Portals display inventory but usually leave trust, context, and follow-up fragmented. Nexus connects the listing to verification, area intelligence, lead ownership, and deal progress for users and agents."],
  ["Facebook groups", "Groups create reach without structured ownership or auditability. Nexus turns demand into qualified, permissioned workflows that can be routed, locked, monitored, and escalated."],
  ["WhatsApp networks", "Private chats lose history and create inconsistent handoffs. Nexus keeps the relevant record, responsibility, and next action attached to the property or deal."],
  ["Traditional brokerage", "Brokerage knowledge is valuable but difficult to scale across markets. Nexus gives professionals governed tools, national context, and AI support while keeping human judgment in control."],
  ["Lead sellers", "Purchased leads create uncertainty about ownership and intent. Nexus protects genuine lead relationships with qualification, locking, monitoring, and auditable lifecycle events."],
  ["Listing directories", "Directories optimize for volume. Nexus optimizes for evidence, structured workflows, and accountable movement from opportunity to outcome."],
] as const;

const trustCards = [
  ["Identity verification", "Identity evidence is reviewed within a controlled workflow so the platform can distinguish a participant from an unknown record. Findings remain auditable and final decisions can escalate to human governance."],
  ["Document verification", "Documents are collected with the property record, checked for completeness and conflicts, and routed to the verification layer. AI recommends; it does not silently approve its own evidence."],
  ["Ownership verification", "Ownership relationships and authority are treated as protected data. No assistant may invent or automatically transfer ownership, and conflicts move to AI Admin review."],
  ["Fraud detection", "Duplicate listings, suspicious accounts, payment anomalies, lead abuse, and document conflicts create risk signals. Fraud Intelligence AI reports rather than hiding uncertainty."],
  ["Audit trails", "Critical actions carry actor, time, reason, before-state, after-state, and escalation evidence. This gives users, operators, and Super Admin a reviewable history."],
  ["Trust infrastructure", "Trust is built from connected records and transparent status, not a decorative badge. Verification, reputation signals, and governance work together across the ecosystem."],
] as const;

const operatingCards = [
  ["Lead qualification", "Declared intent is organized before contact details are shared. Qualification creates a clearer starting point for buyers, sellers, agents, and routing AI."],
  ["Lead assignment", "Routing uses role, location, specialization, eligibility, and recorded ownership rules. A lead is never silently reassigned by an assistant outside its authority."],
  ["Lead lock", "Lead Lock protects the working relationship with a time-bound, auditable state. Abuse signals can escalate while legitimate agents retain visibility of their responsibility."],
  ["Deal creation", "A deal connects buyer, seller, agent, property, documents, milestones, and payment evidence. Every transition becomes a lifecycle event instead of a hidden status change."],
  ["Deal monitoring", "Deal AI watches missing evidence, delayed milestones, negotiation context, and risk signals. Human review remains available for consequential decisions."],
  ["Deal completion", "Completion is a governed state reached through evidence and review, not a message saying a transaction is finished. Disputes and exceptions remain traceable."],
] as const;

const faqs = [
  "What is Nexus OS?", "How is Nexus different from a property portal?", "How are listings verified?", "Can AI approve a property?", "How does Lead Lock work?", "Who owns a lead?", "What does Buyer AI do?", "What does Seller AI do?", "How are agents verified?", "How do agencies manage teams?", "Can investors receive guaranteed ROI?", "How are developers supported?", "What are industrial workflows?", "What can government users access?", "How does AI Admin supervise employees?", "What happens when AI confidence is low?", "How are documents stored?", "How are payment records protected?", "What are the available plans?", "When is human review required?",
];

function Arrow() { return <span aria-hidden="true">-&gt;</span>; }

function ExpandableCards({ items }: Readonly<{ items: readonly (readonly [string, string])[] }>) {
  return <div className="nexus-expand-grid">{items.map(([title, body], index) => <details className="nexus-expand-card" key={title} open={index === 0}><summary><span>{String(index + 1).padStart(2, "0")}</span><strong>{title}</strong><b>+</b></summary><div><p>{body}</p><p className="nexus-card-meta">Benefit: clearer responsibility, safer handoffs, and better ecosystem visibility.</p></div></details>)}</div>;
}

function ArchitectureSection({ eyebrow, title, description, image, children, cta, href }: Readonly<{ eyebrow: string; title: React.ReactNode; description: string; image: string; children: React.ReactNode; cta: string; href: string }>) {
  return <section className="nexus-architecture-section"><div className="nexus-section-head"><div><span className="nexus-eyebrow">{eyebrow}</span><h2>{title}</h2><p>{description}</p></div><img src={image} alt="" /></div>{children}<a className="nexus-cta" href={href}>{cta} <Arrow /></a></section>;
}

export function NexusHomepage() {
  return <main className="nexus-home">
    <section className="nexus-hero"><nav className="nexus-nav"><a href="/" className="nexus-mark">NEXUS <span>OS</span></a><div><a href="/search">Property Graph</a><a href="/ai-workforce">AI Workforce</a><a href="/coverage">Coverage</a><a href="/pricing">Plans</a></div><a className="nexus-nav-action" href="/register">Enter Nexus <Arrow /></a></nav><div className="nexus-hero-grid"><div><span className="nexus-eyebrow">NEXUS PROPERTY NETWORK™ / NEXUS OS™ v5.0</span><h1>Pakistan&apos;s real estate market, <em>operated by intelligence.</em></h1><p>Nexus connects buyers, sellers, agents, agencies, developers, investors, industrial stakeholders, corporate clients, government entities, and a governed AI workforce inside one intelligent property network.</p><div className="nexus-hero-actions"><a className="nexus-button nexus-button-primary" href="/search">Start Property Search <Arrow /></a><a className="nexus-button" href="/list-property">List Your Property</a><a className="nexus-button" href="/register?role=agent">Join As Agent</a><a className="nexus-button" href="/coverage">Explore Coverage</a></div></div><div className="nexus-hero-art"><img src="/nexus/hero" alt="Nexus property intelligence network" /><div className="nexus-orbit-card"><span className="nexus-live-dot" /> AI Admin online<strong>54 employees / 11 divisions</strong></div></div></div><div className="nexus-hero-status"><span>PROPERTY GRAPH <b>PROVINCE → CITY → AREA → ASSET</b></span><span>GOVERNANCE <b>EVERY CRITICAL ACTION AUDITED</b></span><span>NETWORK <b>130+ CITIES / 5,000+ AREAS</b></span></div></section>

  <ArchitectureSection eyebrow="01 / The operating layer" title={<>What is <em>Nexus?</em></>} description="A real estate operating system for the full property lifecycle, not another disconnected listing surface." image="/nexus/intelligence" cta="Explore the Nexus operating model" href="/ai-workforce"><ExpandableCards items={foundation} /></ArchitectureSection>

  <ArchitectureSection eyebrow="02 / Network effect" title={<>Why Nexus is <em>different.</em></>} description="The market already has portals, groups, chats, and brokers. Nexus gives every participant a connected operating layer with evidence and accountability." image="/nexus/cities" cta="Explore the national network" href="/coverage"><ExpandableCards items={differences} /></ArchitectureSection>

  <section className="nexus-role-section"><div className="nexus-section-head"><div><span className="nexus-eyebrow">03 / One network, many operators</span><h2>Built for the people who <em>move property.</em></h2><p>Each role enters a different workflow, sees only what it is permitted to see, and connects to the specialists it needs.</p></div><img src="/nexus/properties" alt="Connected property network" /></div><div className="nexus-role-grid">{roles.map(([role, description, ...items]) => <details className="nexus-role-card" key={role}><summary><span>{role}</span><b>+</b></summary><p>{description}</p><ul>{items.slice(0, 6).map((item) => <li key={item}>{item}</li>)}</ul><a href={items[6]}>Open {role} workflow <Arrow /></a></details>)}</div></section>

  <ArchitectureSection eyebrow="04 / Governed intelligence" title={<>54 AI Employees. <em>One command layer.</em></>} description="Every AI Employee has a defined mission, scoped memory, permission boundary, confidence threshold, and escalation path to AI Admin." image="/nexus/ai-workforce" cta="Meet the AI Workforce" href="/ai-workforce"><div className="nexus-command-strip"><div><span className="nexus-eyebrow">AI ADMIN</span><strong>CEO + COO + Chief Auditor + Chief Security Officer</strong><p>AI Admin supervises approvals, risk signals, audit records, platform health, and escalations without replacing the Super Admin.</p></div><div className="nexus-command-chain"><span>Specialist AI</span><i>→</i><span>Division</span><i>→</i><span>AI Admin</span><i>→</i><span>Super Admin</span></div></div><ExpandableCards items={[["Buyer AI", "Searches approved listings, compares context, and says Not Available when verified data is missing."], ["Seller AI", "Guides structured submissions and collects evidence but cannot publish or approve its own listing."], ["Verification AI", "Coordinates identity, document, property, ownership, and payment evidence for review."], ["Fraud Intelligence AI", "Detects duplicate, suspicious, abusive, and anomalous behavior and escalates risk signals."], ["Investment AI", "Analyzes recorded opportunities and historical metrics without promising ROI or inventing forecasts."], ["AI Admin", "Reviews escalations, governance events, employee behavior, and critical platform conditions."]] as const} /></ArchitectureSection>

  <ArchitectureSection eyebrow="05 / Trust infrastructure" title={<>Verification before <em>visibility.</em></>} description="A property becomes more useful as its evidence, ownership, status, and history become clearer." image="/nexus/verification" cta="Open verification center" href="/verification"><ExpandableCards items={trustCards} /></ArchitectureSection>

  <ArchitectureSection eyebrow="06 / Protected movement" title={<>From lead to deal, <em>auditable.</em></>} description="Nexus connects qualification, ownership, negotiation, documents, payments, milestones, and completion into one lifecycle." image="/nexus/properties" cta="Explore lead protection" href="/lead-protection"><ExpandableCards items={operatingCards} /></ArchitectureSection>

  <section className="nexus-coverage-section"><div className="nexus-section-head"><div><span className="nexus-eyebrow">07 / National coverage</span><h2>Pakistan as a <em>property graph.</em></h2><p>Province, city, area, sector, block, property, lead, deal, owner, agent, and AI memory become navigable relationships.</p></div><img src="/nexus/cities" alt="Pakistan property network map" /></div><div className="nexus-stat-row"><div><strong>130+</strong><span>Cities supported</span></div><div><strong>5,000+</strong><span>Areas supported</span></div><div><strong>7</strong><span>Network regions</span></div><div><strong>∞</strong><span>Graph relationships</span></div></div><a className="nexus-cta" href="/coverage">Browse the coverage network <Arrow /></a></section>

  <section className="nexus-faq-section"><div className="nexus-section-head"><div><span className="nexus-eyebrow">08 / FAQ center</span><h2>Answers with <em>boundaries.</em></h2><p>Start with the operating principles. Expand each answer to understand the workflow behind the promise.</p></div><img src="/nexus/intelligence" alt="Nexus intelligence system" /></div><div className="nexus-faq-grid">{faqs.map((question, index) => <details key={question}><summary><span>{String(index + 1).padStart(2, "0")}</span>{question}<b>+</b></summary><p>Nexus treats this as a governed workflow, not a marketing claim. The relevant specialist uses approved platform records, records its action, explains limitations, and escalates when evidence or confidence is insufficient.</p></details>)}</div><a className="nexus-cta" href="/faq">Open the full FAQ center <Arrow /></a></section>

    <section className="nexus-final-cta"><img src="/nexus/hero" alt="Nexus national property network" /><div><span className="nexus-eyebrow">09 / Join the network</span><h2>Build the future of Pakistan&apos;s property market with <em>Nexus.</em></h2><p>Whether you are a buyer, seller, agent, agency, developer, investor, industrial stakeholder, corporate organization, or government institution, Nexus gives you the infrastructure to operate securely and intelligently at national scale.</p><div className="nexus-hero-actions"><a className="nexus-button nexus-button-primary" href="/register">Create Account <Arrow /></a><a className="nexus-button" href="/coverage">Explore Coverage</a><a className="nexus-button" href="/ai-workforce">Meet AI Workforce</a><a className="nexus-button" href="/search">Start Property Search</a></div></div></section>
  </main>;
}
