import { WorkspaceShell } from "@/components/workspace-shell";
import { aiEmployeeRegistry } from "@/config/ai-constitution";

export default function AIWorkforcePage() {
	const divisions = [...new Set(aiEmployeeRegistry.map((agent) => agent.department))];
	const activeCount = aiEmployeeRegistry.filter((agent) => agent.status === "ACTIVE").length;
	const reviewCount = aiEmployeeRegistry.filter((agent) => agent.confidenceThreshold >= 90).length;

	return <WorkspaceShell active="AI Workforce"><main className="workspace-content"><section className="page-intro"><div><span className="workspace-overline">AI operating layer</span><h2>A governed workforce for every decision.</h2><p>54 scoped employees with explicit authority, memory boundaries, confidence thresholds, and escalation paths.</p></div><span className="workspace-primary">{aiEmployeeRegistry.length} employees governed</span></section><section className="signal-grid"><article className="signal-card green"><span>Governed employees</span><strong>{aiEmployeeRegistry.length}</strong><small>Across {divisions.length} divisions</small></article><article className="signal-card lime"><span>Active workforce</span><strong>{activeCount}</strong><small>One employee in development</small></article><article className="signal-card blue"><span>High-review threshold</span><strong>{reviewCount}</strong><small>90% confidence or higher</small></article><article className="signal-card ink"><span>Audit posture</span><strong>100%</strong><small>Critical actions require logs</small></article></section><div className="ai-workforce-grid">{aiEmployeeRegistry.map((agent) => <article className="ai-agent-card" key={agent.id}><div className="ai-agent-head"><span className="ai-agent-number">{String(agent.id).padStart(2, "0")}</span><span className={`agent-status ${agent.status.toLowerCase()}`}><i /> {agent.status}</span></div><h3>{agent.name}</h3><span className="agent-role">{agent.department} · {agent.confidenceThreshold}% confidence</span><p>{agent.mission}</p><div className="agent-footer"><span>Reports to {agent.reportsTo.replace("_", " ")}</span><button aria-label={`View ${agent.name} governance`} title={`View ${agent.name} governance`}>→</button></div></article>)}</div></main></WorkspaceShell>;
}
