import Link from "next/link";
import { PublicPage } from "@/components/public-page";

const fields = ["Search city or area", "Property type", "Purpose", "Min price", "Max price", "Bedrooms"];
const propertyCards = [["DHA Lahore family home", "Lahore / DHA Phase 6", "Price pending verification"], ["Bahria Town Islamabad plot", "Islamabad / Bahria Town", "Price pending verification"], ["Wapda Town apartment", "Lahore / Wapda Town", "Price pending verification"]] as const;

export default function SearchPage() {
  return <PublicPage eyebrow="National property search" title={<>Find property with <em>context.</em></>} description="Search the Nexus network by location, purpose, property type, and verified status. Live inventory appears as approved records connect to the platform."><section className="public-section"><form className="discovery-grid" action="/search"><label>{fields[0]}<input className="auth-form-input" name="q" placeholder="Lahore, DHA, Bahria Town" /></label>{fields.slice(1).map((field) => <label key={field}>{field}<select name={field.toLowerCase().replaceAll(" ", "-")}><option>Any</option><option>Residential</option><option>Commercial</option><option>Investment</option></select></label>)}<label className="search-toggle"><input type="checkbox" name="verified" /> Verified only</label><button className="button button-primary" type="submit">Search properties <span>-&gt;</span></button></form><div className="section-heading-row" style={{ marginTop: 55 }}><div><p className="kicker">Network results</p><h2>Approved opportunities, clearly marked.</h2></div><span className="row-muted">No live inventory claimed</span></div><div className="public-plans">{propertyCards.map(([title, location, status]) => <article className="public-plan" key={title}><span className="info-index">PROPERTY RECORD</span><h3>{title}</h3><p>{location}</p><p>{status}</p><Link className="button button-outline" href="/register">Create account to view <span>-&gt;</span></Link></article>)}</div></section></PublicPage>;
}
